spring:
  application:
    name: confirmation
  cloud:
    stream:
      bindings:
        confirm-in-0:
          destination: 'payments'
          group: 'payment-processor'
        confirm-out-0:
          destination: 'confirmations'