spring:
  application:
    name: confirmation
  cloud:
    stream:
      bindings:
        confirm-in-0:
          group: 'payments'
          consumer:
            prefetch: 100
        confirm-out-0:
          destination: 'confirmations'