apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: payment-demo
    app.tanzu.vmware.com/deliverable-type: worker
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/workload-type: web
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/workload-name: confirmation
    carto.run/workload-namespace: team-tanzu
  name: confirmation
  namespace: team-tanzu
spec:
  params:
  - name: gitops_ssh_secret
    value: git-secret
  source:
    git:
      ref:
        branch: main
      url: https://github.com/Turbots/gitops.git
    subPath: config/team-tanzu/confirmation