apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: confirmation
  namespace: team-tanzu
  labels:
    app.kubernetes.io/part-of: payment-demo
    apps.tanzu.vmware.com/workload-type: worker
    apps.tanzu.vmware.com/has-tests: 'true'
    apps.tanzu.vmware.com/pipeline: test
spec:
  source:
    git:
      url: https://github.com/Turbots/tanzu-demo.git
      ref:
        branch: main
    subPath: confirmation-service
  build:
    env:
      - name: BP_JVM_VERSION
        value: '17'
      - name: BP_MAVEN_BUILD_ARGUMENTS
        value: '-Dmaven.test.skip=true package'
  serviceClaims:
    - name: broker
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rabbit
  params:
    - name: annotations
      value:
        # Target 10 requests in-flight per pod.
        autoscaling.knative.dev/target: "10"
        # Disable scale to zero with a min scale of 2 for High Availability.
        autoscaling.knative.dev/min-scale: "2"
        # Limit scaling to 10 pods.
        autoscaling.knative.dev/max-scale: "10"