management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: accounts
  cloud:
    stream:
      bindings:
        confirmation-in-0:
          group: accounts